### ISSUE TITLE
How to support schema.org ?

### ISSUE THREAD

**Issue by magick93** [Fannon/mobo#17]
# Background

Mobo makes it easy for developers to design a knowledge model for use in SMW.
There are already very many existing knowledge models, such as owl, uml, schema.org, rdf etc etc

Please see http://schema.org/ and http://schema.org/docs/about.html as this is perhaps the most aligned with SMW.
# Concept

It is likely that some of the concept descriptions on schema.org could match with a mobo users unique knowledge model. It is also likely that mobo users may already have an existing knowledge representation (model). Therefore, it would be helpful if it were possible to generate a project structure, models, fields etc, from, for example, a schema.org schema.

This, then, could also serve as a sample on how to map an existing model to mobo. For example, making it easier to populate mobo from sources such as owl, uml etc.

Thoughts?

**Comment by Fannon** [comment]
Yes, I've thought about this, too.

Since the mobo model is just a collection of YAML files (and from an internal perspective, a collection of data structures), it should be easy to convert existing models to mobo. I already did something like that coming from relational databases. It would also be possible to do it the other way around - convert mobo models into different formats, like UML.

Since version 2, mobo has been rewritten to be a modular framework. What you propse can be implemented though additional transformation layers. (Or with a complete standalone converter script)

But I'm not sure that this would always result in something useful. E.g. schema.org has a very complex  model. This might be OK for the task of data-annotation, but too much for an actual User Interface. It really depends on the source model and on the (default) choices such a conversion tool would make.

If you really think about doing this, we could also talk/chat about it

Best,
Simon

**Comment by magick93** [comment]
> If you really think about doing this, we could also talk/chat about it.

I would like to, but realistically I am already over committed. I am very interested in this project, as another similar projected called [Fresnel Forms] (http://is.cs.ou.nl/OWF/index.php5/Fresnel_Forms). Both products are about making it easy to get a data model into SMW. 

At this stage the things I can help with is testing and documentation. I hope to be able to offer more in the future.

**Comment by Fannon** [comment]
Yes, I can totally understand this (I'm kind of overcommitted right now, too). But testing / documentation is always welcome!
